### ISSUE TITLE
[ ETA03 ] Amy, Kimi (2024-02-07)

### ISSUE THREAD

**Issue by 55555-Jyeon** [mobi-MIMIZ/PostMobism#14]
[ todolist ]

- RTK 공부하기
- auth 로직 공부하기

**Comment by kiminn** [comment]
[ memoirs ]

목데이터를 예정보다 빨리 적용하게 되면서, 오늘의 공부 일정이 살짝 밀렸다
그래도 적용을 미리 해놨으니 앞으로의 작업이 수월할 것으로 예상된다(?)

목데이터를 적용하면서 상태관리 라이브러리의 필요성을 느꼈다
각 컴포넌트 간의 독립성과 재사용성을 향상시키기 위해,
공부한 후 필요하다고 느꼈던 부분들에 적용시켜봐야겠다

나누고싶은 내용이나 이슈가 git issue를 적극 활용해보는 것도 좋을 거 같다
모든 것의 기본은 공식문서라고 하여 공식문서를 먼저 읽어보고 있는데,
변역체라 그런지 조금 어렵고 확실히 recoil 보다 난해한 거 같다

그럼에도 과거의 프로젝트들은 리덕스를 많이 사용하여, 
유지보수 시 사용 될 확률이 높으므로 잘 사용할 줄 알아야겠다!

**Comment by 55555-Jyeon** [comment]
[ memoirs ]

어제 아파서 오래 공부를 못했다, 거의 refreshday.. 🥲
오늘 안에 공부 관련해서는 끝마치고 싶었는데 내일 이어서 RTK 다시 조금 보고 zod + controller 사용법을 숙지해야겠다.

RTK에 대해서 알아보다가 자꾸 redux까지 넘어가게 되어 시간이 좀 오래 걸린 것 같기도..
