### ISSUE TITLE
main pull 받았는데 페이지네이션이 제대로 나오지 않는 거 같습니다!

### ISSUE THREAD

**Issue by kiminn** [mobi-MIMIZ/PostMobism#34]
Amy 님이 올리신 pagination 지금 merge되어있는 것으로 알고있는데,
화면이 제대로 나오지 않는 거 같아서요!

지금 제가  main pull 받은 화면에서는 이렇게 나옵니다!
페이지가 이동이 되지 않구요,

간단하게만 pagination쪽 로직을 봐도 posts가 6개 나와야하는데, 
그렇게 안나오는 거 같아서요..!
혹시 merge과정 중 병합이 잘못된 건지 원래 그런 건지 여쭙니다!
<img width="1680" alt="스크린샷 2024-02-13 오후 10 54 55" src="https://github.com/mobi-MIMIZ/PostMobism/assets/134191815/2fe86ade-842c-43cd-accf-e6ff30a5d96c">

**Comment by 55555-Jyeon** [comment]
아까 제가 올린 버그 이슈랑 관련이 있을 것 같아요
mockPost 개수를 60개 이상으로 불러서 PR했는데 12개 밖에 안 나오는 걸 보니 제대로 병합이 안 된 것 같습니다.

**Comment by kiminn** [comment]
> 아까 제가 올린 버그 이슈랑 관련이 있을 것 같아요 mockPost 개수를 60개 이상으로 불러서 PR했는데 12개 밖에 안 나오는 걸 보니 제대로 병합이 안 된 것 같습니다.
> 
> 지금 PR 올라간 코드들을 보니 최근 코드가 아니네요.. 과정 중 하나인 부분인데.. 다 날아간건가..?

ㅜㅜ 깃 병합과정 중 문제가 있었나보네요 복구되어 다행입니다
고생하셨습니다🩵
