### ISSUE TITLE
refactor 진행에 관하여

### ISSUE THREAD

**Issue by 55555-Jyeon** [mobi-MIMIZ/PostMobism#40]
오늘까지 선승인한 PR 코드 리뷰 다 마치고 내일 refactor 진행하는게 어떤가 싶어 issue 작성합니다 :)

계획대로면 금일까지 기능 구현은 전부 완료가 되어야 하는데 refactoring이 필요할 것 같아서요.

내일 refactor 진행하기 전에 어떤 부분 하면 좋을지 상의해보고
양이 많으면 파트를 나눠 따로 진행하고 별로 없다면 같이 시간 맞춰서 진행하는 것도 좋을 것 같아요!

> 아직 기능 구현이 다 되지 않았다면 내일이 아니어도 되니 일정 맞춰보면 좋을 것 같습니다 😊 
내일 리팩터링 진행 가능한지, 아니면 언제까지 기능 구현이 마무리가 될 것 같은지! <br />
저도 아직 post CRUD가 다 끝나지 않은 상황입니다. 금일 안에 (자정은 넘길 것 같지만..) 가능할 것 같긴 한데.. 또.. 생각보다 에러가 많이 나서 제가 생각한 것보다 조금씩 더 늦어지고 있는 상황이라 확신할 수가 없네요.. 다 끝내기 전까진 안 잘 생각이긴 한데.. 아무튼 Kimi 님도 comment CRUD 하셔야 되는 걸로 알고 있는데 차질 없이 진행되고 있으신가요?

저희 props나 페이지 type들은 한꺼번에 type 폴더 안에 분리하기로 했었던 것도 있고,
코드 리뷰하면서 보니까 서로 약간씩 다른 부분들도 있고, sign-in과 sign-up 등,
파일 구조나 이름 등 어색한 부분들은 같이 교정하면 좋을 것 같아요!

개인적으로 현재 Kimi 님이 만드신 detail-post 와 제가 만든 one-post가 좀 헷갈리더라구요.
제가 만든 one-post는 오히려 create-post 기능을 갖고 있는 파일인데 말이죠.. 👀

우선은 각자 생각나거나 발견하는 부분들 코드 캡쳐해서 여기 댓글로 기록해두면 나중에 리팩터링하기 편할 것 같은데 어떻게 생각하시나요?

**Comment by kiminn** [comment]
알겠습니다! 그렇게 진행하는 거로 알고있겠습니다. 
내일 시간 내서 관련내용 회의해보아요 
저도 오늘안에 끝내는 게 목표였는데 진행이 잘안되고있어요 ㅠ,ㅠ
일단 최대한 해보고있겠습니당 내일 같이 해보도록해요..!

**Comment by 55555-Jyeon** [comment]
main page에 있는 state 전역으로 관리하기

- const [isOpenDetailPost, setIsOpenDetailPost] = useState<boolean>(false)


delete post 기능 구현 후 detail-post의 modal이 닫히지 않음

**Comment by 55555-Jyeon** [comment]
[ refactor ]

main/component/one-post 안에 post-content의 hasImage 전역으로 관리하기

---

[ 이유 ]
main 폴더 안에 있는 post-detail-modal에 hasImage 값이 있을 때만 image들이 크기를 차지할 수 있도록 하기 위해

---

[ 위치 ]

- `src/pages/main/components/one-post/components/post-content.tsx` : 10번째 줄
  const [hasImage, setHasImage] = useState(false)

**Comment by 55555-Jyeon** [comment]
추가하면 좋을 기능

- create post
줄바꿈 적용. 내가 작성한 그대로 줄바꿈 적용되어 올라가면 좋을 것 같다.
현재는 줄바꿈을 해서 올려도 줄바꿈이 되지 않은 채로 create가 되고 있다.

- update post
post의 images들도 추가 업로드 및 삭제하는 기능

**Comment by 55555-Jyeon** [comment]
게시글 삭제 후 게시글 추가 후 바로 render가 되지 않음
새로고침을 해야 반영이 되는 부분 수정 필요할 듯

**Comment by kiminn** [comment]
[ bug ]
일정 개수의 comment들만 보여짐
무한스크롤이 콘솔 찍어보면 잘되는데 어느정도 comment가 쌓이면
과거의 comment가 삭제되어 육안으로 확인이 안됩니다

**Comment by 55555-Jyeon** [comment]
[ issue ] sign-in 

회원가입 후 로그인 시 바로 메인 페이지 이동이 되지 않고 로그인 페이지에 머무르는 이슈가 있습니다.

**Comment by kiminn** [comment]
> [ issue ] sign-in
> 
> 회원가입 후 로그인 시 바로 메인 페이지 이동이 되지 않고 로그인 페이지에 머무르는 이슈가 있습니다.

병합과정중에 잘못됐었던 거 같아요!

지금 메인은 로그인 후 페이지 이동 잘 됩니다

**Comment by kiminn** [comment]
comment 줄바꿈 게시글 scroll 문제..
