### ISSUE TITLE
access-token 관련 문제가 해결되지 않아요

### ISSUE THREAD

**Issue by 55555-Jyeon** [mobi-MIMIZ/PostMobism#42]
post CRUD 진행 중 create 관련 로직(post method)는 refresh token이 있어야 가능해서
refresh token 관련 로직 진행 중입니다.

<img width="1722" src="https://github.com/mobi-MIMIZ/PostMobism/assets/134191817/a430ef3b-0912-44be-95ea-87199b7f680d">

근데 문제가..
refreshToken은 console에 잘 찍히고 있는데 이걸로  access token을 가져오는 부분이 해결되지 않고 있어요.
post 관련 로직 테스트를 진행할 때마다 401 인증 관련 에러가 뜨고 있고, 
network/response 에서는 `{"message":"인증되지 않은 회원입니다"}` 라는 메세지가 보내지고 있습니다.

뭐가 문제일까요..?
현재 post CRUD를 진행하는 중이라 cookie 및 refresh-token 관련 로직은 pos-47 브랜치에 올라가 있습니다. 
한 번 보고 뭐가 문제인 것 같은지 검토 부탁드려요 🥺

저는 조금 다른 거 보다가 다시 봐야 될 것 같아요. 계속 보니 뭐가 문제인지 모르겠어요.

**Comment by kiminn** [comment]
ㅠㅠ 그러게요 저도 같은 오류가 나네요 일부러 방금 회원가입한 아이디의 토큰으로 해보았는데도..
계속 그런 오류가 뜨는.. 저도 계속 한 번 시도해보겠습니당..
<img width="1340" alt="스크린샷 2024-02-15 오후 7 56 47" src="https://github.com/mobi-MIMIZ/PostMobism/assets/134191815/acf0a95d-96bc-4ecc-9486-a3d6814dc58c">

**Comment by 55555-Jyeon** [comment]
**SOLVED...!**

일단 "access_token"을 "accessToken"으로 주고 있었고...
로그인에서 사용했던 TokenRepository와 refresh-token 관련 로직에서 사용했던 cookie로는 headers에 인증 토큰을 실을 수 없었다.

localStorage.getItem으로 하니 해결되었다.

localStorage에서 가져오는 값은 문자열이라 그런가..?
Cross-Origin 관련 에러는 발생하지 않았었는데..! 🤔
